{% set name = "mkdocs-quiz" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocs_quiz-{{ version }}.tar.gz
  sha256: 69e4bc6cfffdaf15ae05849b590a5df7e583ee63fbae2c11cefe1869dd1622d8

build:
  noarch: python
  entry_points:
    - mkdocs-quiz = mkdocs_quiz.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mkdocs >=1.5.0
    - polib >=1.1.0
    - questionary >=2.0.0
    - requests >=2.25.0
    - rich-click >=1.7.0

test:
  imports:
    - mkdocs_quiz
  commands:
    - mkdocs-quiz --help
  requires:
    - python {{ python_min }}

about:
  home: https://ewels.github.io/mkdocs-quiz/
  doc_url: https://ewels.github.io/mkdocs-quiz/
  dev_url: https://github.com/ewels/mkdocs-quiz
  summary: A MkDocs plugin to create interactive quizzes in your markdown.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ewels
    - skyface753
